### ISSUE TITLE
Having Trouble Building

### ISSUE THREAD

**Issue by Rybadour** [haskell-game/bgfx#1]
I'm having trouble building this package which I presume is a prerequisite for building my application. 

My .cabal file:

```
name:                nativeCodeTree
version:             0.1.0.0
synopsis:           
-- description:         
homepage:            N/A
license:             BSD3
license-file:        LICENSE
author:              Ryan Badour
maintainer:          rybadour@gmail.com
-- copyright:           
category:            Development
build-type:          Simple
extra-source-files:  ChangeLog.md
cabal-version:       >=1.10

executable nativeCodeTree
  main-is:             Main.hs
  -- other-modules:       
  other-extensions:    ForeignFunctionInterface, ImplicitParams, OverloadedStrings, PatternSynonyms, ScopedTypeVariables
  build-depends:       base >=4.9 && <4.10, bytestring >=0.10 && <0.11, bgfx
  hs-source-dirs:      src
  build-tools:         hsc2hs
  default-language:    Haskell2010
```

I have the haskell-game/bgfx repo added a git submodule and located in a folder called bgfx at root of my project (next to my .cabal file).

I could not get my project to build with bgfx listed as a dep. so I thought I had to first build the bgfx code. Is that not how this works?

When I tried to build the haskell/bgfx code it said it couldn't find the pkg-config gl package. Any idea how I can get past that?

I'm probably misunderstanding something fundamental so I'd appreciate some guidance.

**Comment by Rybadour** [comment]
Okay I've past that point for now.
I've stumbled my way through `runhaskell Setup.hs configure --user`  but now `runhaskell Setup.hs build` is giving me this problem: https://github.com/bkaradzic/bgfx/issues/215

How can I use makefiles as instructed when cabal is actually building it for me?

**Comment by ocharles** [comment]
Did you get anywhere with this @Rybadour? If you're still struggling, can you provide any steps to reproduce the problem? I'm afraid it's an OSX problem, I might not be able to provide much help.

**Comment by Rybadour** [comment]
No sorry I haven't spend anymore time on this.

**Comment by ocharles** [comment]
Ok, if you don't mind I'm going to close this issue. If you happen to come back to `bgfx` (or I start working on this project again!) please feel free to re-open! Sorry it didn't work out for you.
