### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by walseb** [haskell-game/bgfx#2]
Hi! Thanks for making this package! I'm trying to get this up and running right now, but I'm wondering, why was this abandoned? Were there some wall you hit or was it simply due to lack of time?

**Comment by ocharles** [comment]
Lack of time mainly. It was just done out of personal interest and I had no real motivation to push further I'm afraid!

**Comment by walseb** [comment]
Thanks! The reason I'm asking is because might pick up on development if there aren't any core issues with using bgfx and haskell

**Comment by ocharles** [comment]
If you want commit rights to this repo, just shout - I'll be happy to give them out.
